dist: xenial
sudo: false

language: node_js
node_js:
  - "10"

cache:
  directories:
     - ./node_modules

install:
  - npm install

script:
  - npm run-script build

deploy:
  provider: pages
  skip_cleanup: true
  github_token: 562deea57572435af02c48e3546b9ce304df6bbf
  local_dir: dist/angular-github-pages-travis
  on:
    branch: master
